---
title: "3. Stereographic projections with ggplot"
author: "Tobias Stephan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{3. Stereographic projections with ggplot}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options: 
  markdown: 
    wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, warning=FALSE, message=FALSE}
library(structr)
library(ggplot2)
```



Import and convert to spherical objects:
```{r example}
data(example_planes)

planes <- Plane(example_planes$dipdir, example_planes$dip)
lines <- Line(example_lines$trend, example_lines$plunge)
```

## Stereographic projection
```{r stereo1}
#| fig.alt: >
#|   Diagram showing example data plotted in an
#|   equal-area projection
ggstereo() +
  geom_point(data = gg(planes), aes(x, y, color = "planes")) +
  geom_point(data = gg(lines), aes(x, y, color = "lines")) +
  labs(title = "Example data", color = NULL)
```


Adding great circles:
```{r stereo2}
#| fig.alt: >
#|   Diagram showing example data as greatcircles plotted in an
#|   equal-area projection
ggstereo() +
  geom_path(data = ggl(planes), aes(x, y, color = "planes"), lwd = .1) +
  geom_point(data = gg(lines), aes(x, y, color = "lines")) +
  labs(title = "Example data", color = NULL)
```

## Statistics
```{r stat, message=FALSE,warning=FALSE}
#| fig.alt: >
#|   Diagram showing statistical results of some example data plotted in an
#|   equal-area projection
quality <- runif(nrow(lines), min = 1, max = 45) # assigning a random quality score to the data (can be replaced with real data)

lines_mean <- sph_mean(lines, w = 1 / quality)
lines_delta <- delta(lines, w = 1 / quality)

ggstereo() +
  geom_point(data = gg(lines, quality), aes(x, y, size = quality)) +
  scale_size("Quality", range = c(3, .1)) +
  geom_path(data = ggl(lines_mean, d = lines_delta), aes(x, y, color = "Std"), lwd = .1) +
  geom_point(data = gg(lines_mean), aes(x, y, color = "Mean"), size = 5, shape = 17) +
  labs(title = "Example data", color = NULL)
```

```{r eigen, include = FALSE}
#| fig.alt: >
#|   Diagram showing statistical results of some example data plotted in an
#|   equal-area projection
planes_eigen <- ot_eigen(planes)

ggstereo() +
  geom_point(data = gg(planes), aes(x, y)) +
  geom_path(data = ggl((planes_eigen$vectors), ev = as.character(c(1, 2, 3))), aes(x, y, color = ev), lwd = .1) +
  geom_point(data = gg((planes_eigen$vectors), ev = as.character(c(1, 2, 3))), aes(x, y, color = ev), size = 5, shape = 17) +
  labs(title = "Example data", color = NULL)
```


## Density plots
```{r density, message=FALSE,warning=FALSE}
#| fig.alt: >
#|   Diagram showing the density distribution some example data plotted in an
#|   equal-area projection
ggstereo() +
  geom_contourf_stereo(gg(planes), show.legend = TRUE, norm = TRUE) +
  scale_fill_viridis_d("Density") +
  geom_point(data = gg(planes), aes(x, y)) +
  labs(title = "Example data", color = NULL)
```


## Facets
```{r facets , message=FALSE,warning=FALSE}
#| fig.alt: >
#|   Diagram demonstrating the facet functionality of the ggstereo function
area_l <- LETTERS[sample.int(3, nrow(lines), replace = TRUE)]
area_p <- LETTERS[sample.int(3, nrow(planes), replace = TRUE)]

lines_df <- gg(lines, area = area_l)
planes_df <- ggl(planes, area = area_p)

ggstereo(data = lines_df, aes(x = x, y = y, color = area)) +
  geom_path(data = planes_df, aes(x = x, y = y, group = group), alpha = .25, color = "grey") +
  geom_point() +
  facet_wrap(vars(area)) +
  labs(title = "Example data", color = NULL)
```
