---
title: "Mohr Circle"
author: "Tobias Stephan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Mohr Circle}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options: 
  markdown: 
    wrap: 72
---

This tutorial demonstrates how to use the {structr} package to perform basic stress calculations and visualize the stress state using a Mohr circle.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, warning=FALSE, message=FALSE}
library(structr)
library(ggplot2)
```

Some basic calculations:

```{r stress}
# Define the magnitudes of the principal stress axes
s1 <- 66 # maximum stress, sigma 1
s2 <- 30 # intermediate stress, sigma 2
s3 <- 20 # minimum stress, sigma 3

# Differential stress
diff_stress(s1, s3)

# Mean stress
mean_stress(s1, s3)

# Shear stress at given angle
shear_stress(s1, s3, theta = 35)

# Normal stress at given angle
normal_stress(s1, s3, theta = 35)

# Angle of fracture for given coefficient of internal friction
fracture_angle(mu = 0.6)
```

To plot the Mohr circle, you can either use base R plotting:

```{r mohr1, message=FALSE, warning=FALSE}
#| fig.alt: >
#|   Diagram showing the stress state at some point including the Mohr circle
Mohr_plot(
  sigma1 = s1, sigma2 = s2, sigma3 = s3,
  unit = "MPa", full.circle = TRUE,
  xlim = c(-1, 70), ylim = c(-30, 30)
)

# add the failure criterion
failure_criterion(col = "#B63679", lwd = 2)
```

or ggplot-style plotting:

```{r mohr2, message=FALSE, warning=FALSE}
#| fig.alt: >
#|   Diagram showing the stress state at some point including the Mohr circle
ggMohr(sigma1 = s1, sigma2 = s2, sigma3 = s3, unit = "MPa") +

  # Only show upper half of MohR Circle
  coord_equal(ylim = c(0, NA), expand = FALSE) +

  # select plotting theme
  theme_classic()
```
